### ISSUE TITLE
NullPointerException while interact item with blocks.

### ISSUE THREAD

**Issue by jackey8616** [jackey8616/EconomyExtended#2]
```sh
[01:15:52 WARN]: java.lang.NullPointerException
[01:15:52 WARN]:        at tw.at.clo5de.currency.CurrencyChain.containCurrency(CurrencyChain.java:74)
[01:15:52 WARN]:        at tw.at.clo5de.player.Handler$3.run(Handler.java:99)
[01:15:52 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[01:15:52 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
[01:15:52 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[01:15:52 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[01:15:52 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[01:15:52 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[01:15:52 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by jackey8616** [comment]
The examination is tested under CREATIVE mode, and this issue happens under SURVIVAL mode.
Found out that it is caused by sync check statement in onPlayerUseItem with PlayerInteractEvent.
