### ISSUE TITLE
EventException after player dead.

### ISSUE THREAD

**Issue by jackey8616** [jackey8616/EconomyExtended#3]
~~This occurred after a new player is logged-in and registered.
Still tracing source.~~
This bug occurred after *Player dead*.

```
Spigot===1.12.2
EssentialsX===2.15.0.1
Kycraft===1.0.54
Vault===1.5.6
EconomyExtended===0.0.21
Towny===0.92.0.0
TownyChat===0.49
TownyNameUpdater===1.0
```

```sh
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at com.earth2me.essentials.User.setMoney(User.java:421) [EssentialsX-2.15.0.1.jar:?]
        at com.earth2me.essentials.api.Economy.setMoney(Economy.java:122) [EssentialsX-2.15.0.1.jar:?]
        at com.earth2me.essentials.api.Economy.add(Economy.java:149) [EssentialsX-2.15.0.1.jar:?]
        at com.earth2me.essentials.api.Economy.add(Economy.java:141) [EssentialsX-2.15.0.1.jar:?]
        at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:146) [vault-1.5.6.jar:?]
        at com.palmergames.bukkit.towny.TownyEconomyHandler.add(TownyEconomyHandler.java:350) [Towny.jar:?]
        at com.palmergames.bukkit.towny.object.TownyEconomyObject._collect(TownyEconomyObject.java:84) [Towny.jar:?]
        at com.palmergames.bukkit.towny.object.TownyEconomyObject._payTo(TownyEconomyObject.java:107) [Towny.jar:?]
        at com.palmergames.bukkit.towny.object.TownyEconomyObject.payTo(TownyEconomyObject.java:98) [Towny.jar:?]
        at com.palmergames.bukkit.towny.listeners.TownyEntityMonitorListener.deathPayment(TownyEntityMonitorListener.java:196) [Towny.jar:?]
        at com.palmergames.bukkit.towny.listeners.TownyEntityMonitorListener.onEntityDeath(TownyEntityMonitorListener.java:126) [Towny.jar:?]
        at sun.reflect.GeneratedMethodAccessor173.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:413) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:432) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:956) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:759) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:586) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.EntityLiving.e(EntityLiving.java:1211) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.EntityHuman.e(EntityHuman.java:1508) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.Block.fallOn(Block.java:533) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.Entity.a(Entity.java:1032) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.EntityLiving.a(EntityLiving.java:195) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.EntityPlayer.a(EntityPlayer.java:745) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:686) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
```

**Comment by jackey8616** [comment]
While player death, the event `UserBalanceUpdateEvent` has been call several times.
The line 30 is cause issue because it cann't return the correct value when `event.getPlayer()`.
One of call is return `OfflinePlayer`, and that is why this exception been raise.
